# Generated by Django 2.1.5 on 2019-03-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='copy_from_course',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='title_override',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
