# Generated by Django 2.1.5 on 2019-04-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('visibility', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='school',
            name='opendata_abbr',
            field=models.CharField(default='zz', max_length=2),
            preserve_default=False,
        ),
    ]
