# Generated by Django 2.1.5 on 2019-03-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('IN_PROCESS', 'In Process'), ('CANCELED', 'Canceled'), ('APPROVED', 'Approved'), ('SUBMITTED', 'Submitted'), ('LOCKED', 'Locked')], default='SUBMITTED', max_length=20),
        ),
    ]
