# Generated by Django 2.1.5 on 2019-02-25 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20190225_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='course_requested',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='course.Course'),
        ),
    ]
