# Generated by Django 2.1.5 on 2019-03-01 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20190301_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='masquerade',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
