# Generated by Django 2.1.5 on 2019-03-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20190325_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='additional_instructions',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
