# Generated by Django 2.1.5 on 2019-04-22 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20190422_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_subjects',
        ),
        migrations.AddField(
            model_name='course',
            name='course_subject',
            field=models.ForeignKey(default='MATH', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='course.Subject'),
            preserve_default=False,
        ),
    ]
