# Generated by Django 2.1.5 on 2019-03-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20190328_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='crosslisted',
            field=models.ManyToManyField(blank=True, related_name='_request_crosslisted_+', to='course.Request'),
        ),
    ]
