# Generated by Django 2.1.5 on 2019-04-22 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20190422_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_activity',
            field=models.CharField(choices=[('LEC', 'Lecture'), ('SEM', 'Seminar'), ('LAB', 'Laboratory'), ('CLN', 'Clinic'), ('IND', 'Independent Study'), ('ONL', 'Online Course'), ('PRC', 'SCUE Preceptorial'), ('PRO', 'NSO Proseminar'), ('REC', 'Recitation'), ('SEM', 'Seminar'), ('SRT', 'Senior Thesis'), ('STU', 'Studio'), ('MST', 'Masters Thesis')], max_length=3),
        ),
    ]
