# Generated by Django 2.1.5 on 2019-02-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20190225_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
