# Generated by Django 2.1.5 on 2019-06-28 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20190627_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionalenrollment',
            old_name='course',
            new_name='course_request',
        ),
    ]
