# Generated by Django 2.1.5 on 2019-04-03 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20190403_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='canvas_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canvas', to='course.CanvasSite'),
        ),
    ]
