# Generated by Django 2.1.5 on 2019-03-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_request_crosslisted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='crosslisted',
        ),
        migrations.AddField(
            model_name='course',
            name='crosslisted',
            field=models.ManyToManyField(blank=True, related_name='_course_crosslisted_+', to='course.Course'),
        ),
    ]
