# Generated by Django 2.1.5 on 2019-04-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20190328_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='crosslisted',
            field=models.ManyToManyField(blank=True, default=None, related_name='_course_crosslisted_+', to='course.Course'),
        ),
    ]
