# Generated by Django 2.1.5 on 2019-03-01 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20190301_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='masquerade',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='request',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
