# Generated by Django 2.1.5 on 2019-05-01 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0004_auto_20190422_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penn_id', models.CharField(max_length=10, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='course_activity',
            field=models.CharField(choices=[('LEC', 'Lecture'), ('SEM', 'Seminar'), ('LAB', 'Laboratory'), ('CLN', 'Clinic'), ('IND', 'Independent Study'), ('ONL', 'Online Course'), ('PRC', 'SCUE Preceptorial'), ('PRO', 'NSO Proseminar'), ('REC', 'Recitation'), ('SEM', 'Seminar'), ('SRT', 'Senior Thesis'), ('STU', 'Studio'), ('MST', 'Masters Thesis'), ('UNK', 'Unknown')], max_length=3),
        ),
    ]
