# Generated by Django 2.1.5 on 2019-06-20 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20190501_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='canvas_subaccount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='updatelog',
            name='finished',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
