# Generated by Django 2.1.5 on 2019-06-25 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0007_pagecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('TA', 'TA'), ('INST', 'Instructor'), ('DES', 'Designer'), ('LIB', 'Librarian'), ('OBS', 'Observer')], default='TA', max_length=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='request',
            name='additional_enrollments',
            field=models.ManyToManyField(blank=True, related_name='additional_enrollments', to='course.AdditionalEnrollment'),
        ),
    ]
