# Generated by Django 2.1.5 on 2019-06-25 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20190625_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='additional_enrollments',
        ),
        migrations.AddField(
            model_name='additionalenrollment',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='course.Request'),
        ),
    ]
